global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mcp-server'
    static_configs:
      - targets: ['localhost:9090']  # Assuming your MCP server runs on the host

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']  # Prometheus exporter endpoint of the collector 